#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#define MAX_GENOME 30000
#define MAX_LINE   1024

#define MATCH 1
#define MISMATCH -1
#define GAP -2


int max(int z, int z1, int z3) {
    int m;
    m=z;
    if (z1 > m)
        m = z1;
    if (z3 > m)
        m = z3;

    if (m < 0) 
        return 0;
        

    else  
    return m;
    

}

void smithwatermanmatrix(char Genoma[], char Spike [],int colonne , int righe ) {
   int **matrice = malloc(righe * sizeof(int *));
if (matrice == NULL) {
    printf("Errore di allocazione matrice righe\n");
    exit(1);
}

// Alloca ogni riga
for (int i = 0; i < righe; i++) {
    matrice[i] = calloc(colonne, sizeof(int));  // inizializza a 0
    if (matrice[i] == NULL) {
        printf("Errore di allocazione matrice colonna\n");
        exit(1);
    }
}

       

for(int riga=1 ;riga<righe;riga=riga+1){ 

    for(int colonna=1 ;colonna<colonne;colonna=colonna+1){ 
    int z=0;
    int z1=0;
    int z2=0;
    int z3=0;
    //W=Gopen​+(n−1)⋅Gextension​
    z=matrice[riga][colonna-1]+GAP;
    z1=matrice[riga-1][colonna]+GAP;
 
        if(Genoma[colonna-1]==Spike[riga-1]) {
        z2=MATCH;
        }
        else {
        z2=MISMATCH;
        }
    z3=matrice[riga-1][colonna-1]+z2;
        if(z<0) {
        z=0;
        }
        if(z1<0) {
        z1=0;
        }
        if(z3<0) {
        z3=0;
        }
    matrice[riga][colonna]=max(z,z1,z3);
}

} 
int massimo =0;
int x=0;
int y=0;
        
for (int riga= 0; riga <righe; riga++) {
  
for (int colonna= 0; colonna <colonne; colonna++){
if (matrice[riga][colonna]>massimo) {
    massimo=matrice[riga][colonna];
    x=riga;
    y=colonna;
    }
  
}
 
}    

  printf ("il massimo è %d, è in posizione riga %d colonna %d \n",massimo,x, y);  
int Fine;
Fine=y;
int msm=0;
int gapsd=0;
int gapsi=0;
do {

int maxm=0;
int R=0;
int R1 =0;
int R3=0;
R=matrice[x-1][y-1];
R1=matrice[x-1][y];
R3=matrice[x][y-1];
maxm=max(R,R1,R3);
if(maxm==R) {
y=y-1;
x=x-1;
  if(Genoma[y]!=Spike[x]) 
     msm=msm+1;
    //printf("missmatch in posizione %d \n",y);
        
}
else if(maxm==R1) {
    gapsd=gapsd+1;
y=y;
x=x-1;   
//printf("delezione rispetto alla spike in posizione %d \n", y);
}
else if(maxm==R3) {
    gapsi=gapsi+1;
y=y-1;
x=x;   
//printf("inserzione rispetto alla spike in posizione %d \n", y);
}


} while(matrice[x][y]!=0);

printf( "la spike inzia in posizione %d , e finisce in posizone %d ci sono %d mismatch %d inserzioni e %d delezioni \n",y+1,Fine,msm, gapsi, gapsd );
printf("la spike è lunga %d basi\n",Fine-(y+1));
for (int i = 0; i < righe; i++) {
    free(matrice[i]);
}
free(matrice);



}    



int main(void) {
    
   
  FILE *FILEGENOMA= fopen("ILLINOIS.fasta", "r");//APERTURA FILE 
    if (FILEGENOMA == NULL) {
        perror("Errore apertura file");
        return 1;
    }
    char GENOMA[MAX_GENOME + 1];  // +1 per '\0'

    char lineGenoma[MAX_LINE];
        int lenGenoma = 0;

    while (fgets(lineGenoma, MAX_LINE, FILEGENOMA)) {   // MESSO IL FILE NELL'ARRAY

        // Salta intestazione
        if (lineGenoma[0] == '>') continue;

        // Rimuove newline
        lineGenoma[strcspn(lineGenoma, "\n")] = '\0';

        // Copia caratteri uno a uno
        for (int i = 0; lineGenoma[i] != '\0'; i++) {
            if (lenGenoma < MAX_GENOME) {
                GENOMA[lenGenoma] = lineGenoma[i];
                lenGenoma++;
            }
        }
    }

    GENOMA[lenGenoma] = '\0';
   fclose(FILEGENOMA); // CHIUSURA FILE 
 
   printf("Lunghezza del genoma: %d basi\n", lenGenoma); 


char rif_spike[]="ATGTTTGTTTTTCTTGTTTTATTGCCACTAGTCTCTAGTCAGTGTGTTAATCTTACAACCAGAACTCAATTACCCCCTGCATACACTAATTCTTTCACACGTGGTGTTTATTACCCTGACAAAGTTTTCAGATCCTCAGTTTTACATTCAACTCAGGACTTGTTCTTACCTTTCTTTTCCAATGTTACTTGGTTCCATGCTATACATGTCTCTGGGACCAATGGTACTAAGAGGTTTGATAACCCTGTCCTACCATTTAATGATGGTGTTTATTTTGCTTCCACTGAGAAGTCTAACATAATAAGAGGCTGGATTTTTGGTACTACTTTAGATTCGAAGACCCAGTCCCTACTTATTGTTAATAACGCTACTAATGTTGTTATTAAAGTCTGTGAATTTCAATTTTGTAATGATCCATTTTTGGGTGTTTATTACCACAAAAACAACAAAAGTTGGATGGAAAGTGAGTTCAGAGTTTATTCTAGTGCGAATAATTGCACTTTTGAATATGTCTCTCAGCCTTTTCTTATGGACCTTGAAGGAAAACAGGGTAATTTCAAAAATCTTAGGGAATTTGTGTTTAAGAATATTGATGGTTATTTTAAAATATATTCTAAGCACACGCCTATTAATTTAGTGCGTGATCTCCCTCAGGGTTTTTCGGCTTTAGAACCATTGGTAGATTTGCCAATAGGTATTAACATCACTAGGTTTCAAACTTTACTTGCTTTACATAGAAGTTATTTGACTCCTGGTGATTCTTCTTCAGGTTGGACAGCTGGTGCTGCAGCTTATTATGTGGGTTATCTTCAACCTAGGACTTTTCTATTAAAATATAATGAAAATGGAACCATTACAGATGCTGTAGACTGTGCACTTGACCCTCTCTCAGAAACAAAGTGTACGTTGAAATCCTTCACTGTAGAAAAAGGAATCTATCAAACTTCTAACTTTAGAGTCCAACCAACAGAATCTATTGTTAGATTTCCTAATATTACAAACTTGTGCCCTTTTGGTGAAGTTTTTAACGCCACCAGATTTGCATCTGTTTATGCTTGGAACAGGAAGAGAATCAGCAACTGTGTTGCTGATTATTCTGTCCTATATAATTCCGCATCATTTTCCACTTTTAAGTGTTATGGAGTGTCTCCTACTAAATTAAATGATCTCTGCTTTACTAATGTCTATGCAGATTCATTTGTAATTAGAGGTGATGAAGTCAGACAAATCGCTCCAGGGCAAACTGGAAAGATTGCTGATTATAATTATAAATTACCAGATGATTTTACAGGCTGCGTTATAGCTTGGAATTCTAACAATCTTGATTCTAAGGTTGGTGGTAATTATAATTACCTGTATAGATTGTTTAGGAAGTCTAATCTCAAACCTTTTGAGAGAGATATTTCAACTGAAATCTATCAGGCCGGTAGCACACCTTGTAATGGTGTTGAAGGTTTTAATTGTTACTTTCCTTTACAATCATATGGTTTCCAACCCACTAATGGTGTTGGTTACCAACCATACAGAGTAGTAGTACTTTCTTTTGAACTTCTACATGCACCAGCAACTGTTTGTGGACCTAAAAAGTCTACTAATTTGGTTAAAAACAAATGTGTCAATTTCAACTTCAATGGTTTAACAGGCACAGGTGTTCTTACTGAGTCTAACAAAAAGTTTCTGCCTTTCCAACAATTTGGCAGAGACATTGCTGACACTACTGATGCTGTCCGTGATCCACAGACACTTGAGATTCTTGACATTACACCATGTTCTTTTGGTGGTGTCAGTGTTATAACACCAGGAACAAATACTTCTAACCAGGTTGCTGTTCTTTATCAGGATGTTAACTGCACAGAAGTCCCTGTTGCTATTCATGCAGATCAACTTACTCCTACTTGGCGTGTTTATTCTACAGGTTCTAATGTTTTTCAAACACGTGCAGGCTGTTTAATAGGGGCTGAACATGTCAACAACTCATATGAGTGTGACATACCCATTGGTGCAGGTATATGCGCTAGTTATCAGACTCAGACTAATTCTCCTCGGCGGGCACGTAGTGTAGCTAGTCAATCCATCATTGCCTACACTATGTCACTTGGTGCAGAAAATTCAGTTGCTTACTCTAATAACTCTATTGCCATACCCACAAATTTTACTATTAGTGTTACCACAGAAATTCTACCAGTGTCTATGACCAAGACATCAGTAGATTGTACAATGTACATTTGTGGTGATTCAACTGAATGCAGCAATCTTTTGTTGCAATATGGCAGTTTTTGTACACAATTAAACCGTGCTTTAACTGGAATAGCTGTTGAACAAGACAAAAACACCCAAGAAGTTTTTGCACAAGTCAAACAAATTTACAAAACACCACCAATTAAAGATTTTGGTGGTTTTAATTTTTCACAAATATTACCAGATCCATCAAAACCAAGCAAGAGGTCATTTATTGAAGATCTACTTTTCAACAAAGTGACACTTGCAGATGCTGGCTTCATCAAACAATATGGTGATTGCCTTGGTGATATTGCTGCTAGAGACCTCATTTGTGCACAAAAGTTTAACGGCCTTACTGTTTTGCCACCTTTGCTCACAGATGAAATGATTGCTCAATACACTTCTGCACTGTTAGCGGGTACAATCACTTCTGGTTGGACCTTTGGTGCAGGTGCTGCATTACAAATACCATTTGCTATGCAAATGGCTTATAGGTTTAATGGTATTGGAGTTACACAGAATGTTCTCTATGAGAACCAAAAATTGATTGCCAACCAATTTAATAGTGCTATTGGCAAAATTCAAGACTCACTTTCTTCCACAGCAAGTGCACTTGGAAAACTTCAAGATGTGGTCAACCAAAATGCACAAGCTTTAAACACGCTTGTTAAACAACTTAGCTCCAATTTTGGTGCAATTTCAAGTGTTTTAAATGATATCCTTTCACGTCTTGACAAAGTTGAGGCTGAAGTGCAAATTGATAGGTTGATCACAGGCAGACTTCAAAGTTTGCAGACATATGTGACTCAACAATTAATTAGAGCTGCAGAAATCAGAGCTTCTGCTAATCTTGCTGCTACTAAAATGTCAGAGTGTGTACTTGGACAATCAAAAAGAGTTGATTTTTGTGGAAAGGGCTATCATCTTATGTCCTTCCCTCAGTCAGCACCTCATGGTGTAGTCTTCTTGCATGTGACTTATGTCCCTGCACAAGAAAAGAACTTCACAACTGCTCCTGCCATTTGTCATGATGGAAAAGCACACTTTCCTCGTGAAGGTGTCTTTGTTTCAAATGGCACACACTGGTTTGTAACACAAAGGAATTTTTATGAACCACAAATCATTACTACAGACAACACATTTGTGTCTGGTAACTGTGATGTTGTAATAGGAATTGTCAACAACACAGTTTATGATCCTTTGCAACCTGAATTAGACTCATTCAAGGAGGAGTTAGATAAATATTTTAAGAATCATACATCACCAGATGTTGATTTAGGTGACATCTCTGGCATTAATGCTTCAGTTGTAAACATTCAAAAAGAAATTGACCGCCTCAATGAGGTTGCCAAGAATTTAAATGAATCTCTCATCGATCTCCAAGAACTTGGAAAGTATGAGCAGTATATAAAATGGCCATGGTACATTTGGCTAGGTTTTATAGCTGGCTTGATTGCCATAGTAATGGTGACAATTATGCTTTGCTGTATGACCAGTTGCTGTAGTTGTCTCAAGGGCTGTTGTTCTTGTGGATCCTGCTGCAAATTTGATGAAGACGACTCTGAGCCAGTGCTCAAAGGAGTCAAATTACATTACACATAA";
char rif_nsp2[]="GCATACACTCGCTATGTCGATAACAACTTCTGTGGCCCTGATGGCTACCCTCTTGAGTGCATTAAAGACCTTCTAGCACGTGCTGGTAAAGCTTCATGCACTTTGTCCGAACAACTGGACTTTATTGACACTAAGAGGGGTGTATACTGCTGCCGTGAACATGAGCATGAAATTGCTTGGTACACGGAACGTTCTGAAAAGAGCTATGAATTGCAGACACCTTTTGAAATTAAATTGGCAAAGAAATTTGACACCTTCAATGGGGAATGTCCAAATTTTGTATTTCCCTTAAATTCCATAATCAAGACTATTCAACCAAGGGTTGAAAAGAAAAAGCTTGATGGCTTTATGGGTAGAATTCGATCTGTCTATCCAGTTGCGTCACCAAATGAATGCAACCAAATGTGCCTTTCAACTCTCATGAAGTGTGATCATTGTGGTGAAACTTCATGGCAGACGGGCGATTTTGTTAAAGCCACTTGCGAATTTTGTGGCACTGAGAATTTGACTAAAGAAGGTGCCACTACTTGTGGTTACTTACCCCAAAATGCTGTTGTTAAAATTTATTGTCCAGCATGTCACAATTCAGAAGTAGGACCTGAGCATAGTCTTGCCGAATACCATAATGAATCTGGCTTGAAAACCATTCTTCGTAAGGGTGGTCGCACTATTGCCTTTGGAGGCTGTGTGTTCTCTTATGTTGGTTGCCATAACAAGTGTGCCTATTGGGTTCCACGTGCTAGCGCTAACATAGGTTGTAACCATACAGGTGTTGTTGGAGAAGGTTCCGAAGGTCTTAATGACAACCTTCTTGAAATACTCCAAAAAGAGAAAGTCAACATCAATATTGTTGGTGACTTTAAACTTAATGAAGAGATCGCCATTATTTTGGCATCTTTTTCTGCTTCCACAAGTGCTTTTGTGGAAACTGTGAAAGGTTTGGATTATAAAGCATTCAAACAAATTGTTGAATCCTGTGGTAATTTTAAAGTTACAAAAGGAAAAGCTAAAAAAGGTGCCTGGAATATTGGTGAACAGAAATCAATACTGAGTCCTCTTTATGCATTTGCATCAGAGGCTGCTCGTGTTGTACGATCAATTTTCTCCCGCACTCTTGAAACTGCTCAAAATTCTGTGCGTGTTTTACAGAAGGCCGCTATAACAATACTAGATGGAATTTCACAGTATTCACTGAGACTCATTGATGCTATGATGTTCACATCTGATTTGGCTACTAACAATCTAGTTGTAATGGCCTACATTACAGGTGGTGTTGTTCAGTTGACTTCGCAGTGGCTAACTAACATCTTTGGCACTGTTTATGAAAAACTCAAACCCGTCCTTGATTGGCTTGAAGAGAAGTTTAAGGAAGGTGTAGAGTTTCTTAGAGACGGTTGGGAAATTGTTAAATTTATCTCAACCTGTGCTTGTGAAATTGTCGGTGGACAAATTGTCACCTGTGCAAAGGAAATTAAGGAGAGTGTTCAGACATTCTTTAAGCTTGTAAATAAATTTTTGGCTTTGTGTGCTGACTCTATCATTATTGGTGGAGCTAAACTTAAAGCCTTGAATTTAGGTGAAACATTTGTCACGCACTCAAAGGGATTGTACAGAAAGTGTGTTAAATCCAGAGAAGAAACTGGCCTACTCATGCCTCTAAAAGCCCCAAAAGAAATTATCTTCTTAGAGGGAGAAACACTTCCCACAGAAGTGTTAACAGAGGAAGTTGTCTTGAAAACTGGTGATTTACAACCATTAGAACAACCTACTAGTGAAGCTGTTGAAGCTCCATTGGTTGGTACACCAGTTTGTATTAACGGGCTTATGTTGCTCGAAATCAAAGACACAGAAAAGTACTGTGCCCTTGCACCTAATATGATGGTAACAAACAATACCTTCACACTCAAAGGCGGT";

printf("\nLunghezza della sequenza spike di WUHAN 1 è: %zu basi \n", strlen(rif_spike));



// Spike con 'Z' iniziale
char rif_spike_Z[3823];
rif_spike_Z[0] = 'Z';
for(int i = 0; i < 3823; i++) {
    rif_spike_Z[i+1] = rif_spike[i];
}
char GENOMA_Z[lenGenoma + 1];  // +1 per 'Z'

GENOMA_Z[0] = 'Z';  // primo elemento = Z

// Copia il resto del genoma
    for (int i = 0; i < lenGenoma; i++) {
    GENOMA_Z[i + 1] = GENOMA[i];
    }


       int righe=3823;
       int colonne=lenGenoma+1;
    //smithwatermanmatrix(GENOMA_Z,rif_spike_Z,colonne,righe);
    char idiciassetteiniziali[18];
    char idiciassettefinali[18];
    int x1;
    int x2;
    int max1=0;
    int max2=0;
    int c1;
    int c2;
        for( int i =0 ; i<18; i=i+1) {
   
            idiciassetteiniziali[i]=rif_spike_Z[i];

            }
      
         int j=0;
         
         for(int i=3821-17; i<3823; i=i+1) {
            j++;
            
            idiciassettefinali[j]=rif_spike[i];

            }
      
         for( int i=1;  i<lenGenoma-17; i=i+1){
                  c1=0;
                  c2=0;
            for( int j=1;  j<18; j++){
        
                if(GENOMA_Z[i+j-1]==idiciassetteiniziali[j]) {
                c1++;
                }
           
                if(GENOMA_Z[i+j-1]==idiciassettefinali[j]) {
                c2++;
                }
                }

        if(c1>max1) {
            max1=c1;
            x1=i;
            }
        if(c2>max2) {
        max2=c2;
        x2=i+17;
        }

    }
    printf("%d e %d\n", x1, x2);
    
    

    return 0;


}

